# Coursework

## CSci 39542: Introduction to Data Science

**Department of Computer Science, Hunter College, City University of New York**  
**Spring 2026**

---

All students must join the course's gradescope using the provided access code: **PK36RW**. Students must verify that their Gradescope account has their full name and CUNY email address in the account settings (Account > Edit Account).

---


 Unless otherwise noted, classwork is submitted via Gradescope. Access information is given during the corresponding lecture. To get the most out of lecture, bring a device with you to lecture with a development environment (IDE) that has Python 3+ (preferrably the same that you plan to use for technical interviews). 

**Do not say you were in the room if you did not attend.** Lying about attendance obtains an unfair advantage and will be submitted to the Office of Student Conduct. It is not worth the points (that would have been replaced anyway by your final exam score) for a record of academic dishonesty that is kept by both the department and college. The suggested sanction for lying is a 0 on this classwork and the loss of the replacement policy for missed lecture grades. Note: while we suggest a sanction, the final decision about the severity of the sanction is by the Office of Student Conduct. 

---

### Week 1

#### Classwork 1

*Due 11:30am, Thursday, 04 September.*  

Available during Lecture 1 on Gradescope, this classwork introduces the autograder that is used for the programming assignments.  The structure of the sample program mirrors the structure and content of the upcoming Program 1 (which we will start in the second part of Lecture 1).  
    
Write a function that takes the name of a file and makes a dictionary of the lines of the file.
          
- `make_dict(file_name, sep=': ')`:  Takes a name of a file (file_name) and a delimiter (sep), where the default value is ': '.  If a line of the file does not include sep, the line should be ignored.   Otherwise, for each line, the string preceding the delimiter sep is the key, and the string after sep is the value.  Your function returns the dictionary.
          
For example, assuming these functions are in a file, `cw1.py` and run on a file containing names that start with 'A', [contacts.txt](../attachments/contacts.txt):

In [ ]:
contacts = cw1.make_dict('contacts.txt')
who = 'CS Department'
print(f'Contact info for {who} is {contacts[who]}.')

will print:

`Contact info for CS Department is 10th Floor HN, x5213.`   

Another example with [nick_names.txt](../attachments/nick_names.txt): 

In [ ]:
nick_names = cw1.make_dict('nick_names.txt', sep = ' ')
names = ['Beth','Lisa','Meg','Greta','Amy','Mia']
for n in names:
  print(f'Full name for {n} is {nick_names[n]}.')

will print:


    Full name for Beth is Elizabeth.
    Full name for Lisa is Elizabeth.
    Full name for Meg is Margaret.
    Full name for Greta is Margaret.
    Full name for Amy is Amelia.
    Full name for Mia is Amelia.

If you attended lecture, include the last line to the introductory comment:

In [ ]:
"""
Name:  YOUR_NAME
Email: YOUR_EMAIL
Resources:  RESOURCES USED
I attended lecture today.
"""

If you did not attend lecture, do not include the last line.

---

### Week 2

#### Classwork 2

*Due 11:30am, Monday, 08 September.*  

Available during Lecture 2 on Gradescope, this classwork asks that you write a program using Pandas and its file I/O. To get the most out of this exercise, bring a laptop with you to lecture with a development environment (IDE) that has Python 3.6+ to work through in lecture. 
    
Write a program that asks the user for the name of an input CSV file and the name of an output CSV file. The program should open the file name provided by the user. Next, the program should select rows where the field `Grade` is equal to 3 and the `Year` is equal to 2019 and write all rows that match that criteria to a new CSV file. 

 Then a sample run of the program: 

```txt
Enter input file name: school-ela-results-2013-2019.csv
Enter output file name:  ela2013.csv
```

where the file [school-ela-results-2013-2019.csv](../attachments/school_ELA_2013_2019.csv) is extracted from NYC Schools Test Results. The first lines of the output file would be: 

```txt
School,Name,Grade,Year,Category,Number Tested,Mean Scale Score,# Level 1,% Level 1,# Level 2,% Level 2,# Level 3,% Level 3,# Level 4,% Level 4,# Level 3+4,% Level 3+4
01M015,P.S. 015 ROBERTO CLEMENTE,3,2019,All Students,27,606,1,3.7,7,25.9,18,66.7,1,3.7,19,70.4
01M019, P.S. 019 ASHER LEVY,3,2019,All Students,24,606,0,0.0,8,33.3,15,62.5,1,4.2,16,66.7
01M020,P.S. 020 ANNA SILVER,3,2019,All Students,57,593,13,22.8,24,42.1,18,31.6,2,3.5,20,35.1
```

Hints: 

* Since the `Grade` column contains a mixtures of numbers (e.g. 3) and strings ("All Grades"), the column is stored as strings. 

If you attended lecture, include the last line in the introductory comment: 

In [ ]:
"""
Name:  YOUR_NAME
Email: YOUR_EMAIL
Resources:  RESOURCES USED
I attended lecture today.
"""

### Week 5

#### Classwork 7

*Due 11:59pm, Monday, 29 September.*  

Available during Lecture 7 on Gradescope, this classwork focuses on hiring in the technical sector. 2022 fall, hiring looked quite strong. Here's a an analysis by [Prof. Stevenson](https://fordschool.umich.edu/faculty/betsey-stevenson) of University of Michigan:


![stevenson_info_jobs_dec_2022.png](../attachments/stevenson_info_jobs_dec_2022.png)

[BLS Monthly Jobs Report: Rapid Insights from Betsey Stevenson](https://poverty.umich.edu/2022/12/02/november-jobs-report-strong-job-growth-continues-but-there-are-hints-of-weakness/).

Including more recent numbers show growth but not as quickly:

<!-- Using the data set for the previous 5 years from [St. Louis Federal Reserve Economic Data Data (FRED)](https://fred.stlouisfed.org/series/USINFO): -->

![tech_jobs_fred_1940_2023.png](../attachments/tech_jobs_fred_1940_2023.png)

*Available Libraries: pandas, numpy, sklearn.linear_model, pickle.*

Using the data set for 2010 until August 2023 from [St. Louis Federal Reserve Economic Data Data (FRED)](https://fred.stlouisfed.org/series/USINFO):

	[fred_info_2010_aug_2023.csv](../attachments/fred_info_2010_aug_2023.csv): A CSV file with the employment in Information Services since 2010 (until August 2023).
write functions that will fit a linear regression to the data and predicts the number of jobs on January 1, 2024:

- `fit_linear_regression(df)`: This function takes one input:

	- `df`: containing an index and the column, `USINFO`.

Fits a linear model to `index` and `????`, using `sklearn.linear_model.LinearRegression` (see lecture & textbook for details on setting up the model). The resulting model should be returned as bytestream, using [pickle](https://docs.python.org/3/library/pickle.html) (see Lecture 4).

*Hint: Since each entry is exactly 1 month apart, you can use the index, instead of parsing the datetime{.inline} objects. You may find `df.index.to_series()` useful.*

`predict(mod_pkl, offset)`: This function takes two inputs:

- `mod_pkl`: a trained model for the data, stored in pickle format.
- `offset`: the number of months since January 1, 2010.
  
Using the model, `mod_pkl`, returns the predicted number of employees in Information Services `offset` months from January 1, 2010. For example if `offset` is `180`, then it would return the model's prediction of the number of employees `180/12 = 15` years after the baseline (January 2010) or January 2025. 

For example:

In [2]:
df = pd.read_csv(directory+'fred_info_2010_aug_2023.csv')
mod_pkl = fit_linear_regression(df)
januarys = pd.DataFrame({'index' : list(range(120,240,12))})
predictions = predict(mod_pkl,januarys)
print(f'The predicted employments by years:')
results = zip(list(range(2020,2030)),predictions)
for year,pred in results:
    print(f'January {year}: \t {int(pred*1000):,}')

NameError: name 'pd' is not defined

gives the model's predictions for employment from 2020 to 2030:

In [ ]:
"""
The predicted employments by years:
January 2020:    2,879,867
January 2021:    2,905,173
January 2022:    2,930,480
January 2023:    2,955,786
January 2024:    2,981,092
January 2025:    3,006,398
January 2026:    3,031,705
January 2027:    3,057,011
January 2028:    3,082,317
January 2029:    3,107,623
"""

### Week 6
#### Classwork 9
*Due 11:59pm, Thursday, 9 October.*
Available during Lecture 9 on Gradescope, the learning objective of this classwork is to increase understanding of smoothing and gain fluidity with using distributions for smoothing. To get the most out of this exercise, bring a laptop with you to lecture with a development environment (IDE) that has Python 3.6+ to work through in lecture. 

In [Section 11.2](https://learningds.org/ch/11/viz_smoothing.html), we used smoothing to visualize data. For this program, write a function that takes two arguments, an Numpy array of x-axis coordinates, and a list of numeric values, and returns the corresponding y-values for the sum of the gaussian probability distribution functions (pdf's) for each point in the list.

- `computeSmoothing(xes,points)`: This function takes a numpy array `xes` and a list, `points`, of numeric values. For each `p` in `points`, the function should compute the normal probability distribution function (`scipy.norm.pdf`) centered at `loc = p` with standard deviation `scale = 0.5` for all values in `xes`. The return value is a numpy array of the sum of these at each point.

For example, calling the function:

```
xes = np.linspace(0, 10, 1000)
density = computeSmoothing(xes,[5])
plt.plot(xes,density)
plt.show()
```

would give the plot:

![](https://stjohn.github.io/teaching/data/fall21/density5.png)

since there is only one point given (namely 5), the returned value is the probability density function centered at 5 (with `scale = 0.5`) computed for each of the `xes`.

For example, calling the function:

```
pts = [2,2,5,5,2,3,4,6,7,9]
xes = np.linspace(0, 10, 1000)
density = computeSmoothing(xes,pts)
plt.plot(xes,density)
plt.fill_between(xes,density)
plt.show()
```

would give the plot:

![](https://stjohn.github.io/teaching/data/fall21/density_fillBetween.png)

since the there are 10 points given, the function computes the probability density function centered at each of the points, across all the values in `xes`. It then sums up these contributions and returns an array of the same length as `xes`.

Note: you should submit a file with only the standard comments at the top, and this function. The grading scripts will then import the file for testing. If you attended lecture, include in the introductory comment the three lines detailed in Classwork 2

### Week 7

#### Classwork 10

*Due 11:59pm, Tuesday, 14 October.*   
Available during Lecture 10 on Gradescope, this classwork introduces the canonical digits dataset and uses sci-kit learn to build logistic regression
models. To get the most out of this exercise, bring a laptop with you to
lecture with a development environment (IDE) that has Python 3+ to work
through in lecture.

This program uses the canonical [MNIST dataset of hand-written
digits](https://en.wikipedia.org/wiki/MNIST_database) and available in
[sklearn digits dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html):


![mnist_digits.png](../attachments/sklearn_digits.png)

The dataset has 1797 scans of hand-written digits. Each entry has the
digit represented (`target`) as well as the 64 values
representing the gray scale for the 8 x 8 image. The first 5 entries
are:


The gray scales for the first 5 entries, flattened to one dimensional
array:


``` text
[[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3. 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
 [ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.  3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16. 16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]
 [ 0.  0.  0.  4. 15. 12.  0.  0.  0.  0.  3. 16. 15. 14.  0.  0.  0.  0.  8. 13.  8. 16.  0.  0.  0.  0.  1.  6. 15. 11.  0.  0.  0.  1.  8. 13. 15.  1.  0.  0.  0.  9. 16. 16.  5.  0.  0.  0.  0.  3. 13. 16. 16. 11.  5.  0.  0.  0.  0.  3. 11. 16.  9.  0.]
 [ 0.  0.  7. 15. 13.  1.  0.  0.  0.  8. 13.  6. 15.  4.  0.  0.  0.  2.  1. 13. 13.  0.  0.  0.  0.  0.  2. 15. 11.  1.  0.  0.  0.  0.  0.  1. 12. 12.  1.  0.  0.  0.  0.  0.  1. 10.  8.  0.  0.  0.  8.  4.  5. 14.  9.  0.  0.  0.  7. 13. 13.  9.  0.  0.]
 [ 0.  0.  0.  1. 11.  0.  0.  0.  0.  0.  0.  7.  8.  0.  0.  0.  0.  0.  1. 13.  6.  2.  2.  0.  0.  0.  7. 15.  0.  9.  8.  0.  0.  5. 16. 10.  0. 16.  6.  0.  0.  4. 15. 16. 13. 16.  1.  0.  0.  0.  0.  3. 15. 10.  0.  0.  0.  0.  0.  2. 16.  4.  0.  0.]]
```


Today, we will focus on entries that represent 0\'s and 1\'s. The first
10 from the dataset are displayed below:


![mnist_digits](../attachments/mnist_first5.png)

Write a function that builds a logistic regression model that classifies
binary digits:

- `def binary_digit_clf(data, target, test_size = 0.25, random_state = 21):`:
  This function has four inputs:
  - `data`: a numpy array that includes rows of equal size
    flattend arrays,
  - `target` a numpy array that takes values 0 or 1
    corresponding to the rows of `data`.
  - `test_size`: the size of the test set created when the data
    is divided into test and training sets with
    [train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html).
    The default value is `0.25`.
  - `random_state`: the random seed used when the data is
    divided into test and training sets with
    [train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html).
    The default value is `21`.

  The function returns the [confusion
  matrix](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html)
  that results.

For example, let\'s flatten the entries and restrict the dataset to just
binary digits:


```py
#Import datasets, classifiers and performance metrics:
from sklearn import datasets, svm, metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
#Using the digits data set from sklearn:
from sklearn import datasets
digits = datasets.load_digits()
print(digits.target)
print(type(digits.target), type(digits.data))
#flatten the images
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))
print(data[0:5])
print(f'The targets for the first 5 entries: {digits.target[:5]}')
#Make a DataFrame with just the binary digits:
binaryDigits = [(d,t) for (d,t) in zip(data,digits.target) if t <= 1]
bd,bt = zip(*binaryDigits)
print(f'The targets for the first 5 binary entries: {bt[:5]}')
```


which will print:


``` text

[0 1 2 ... 8 9 8]
   
[[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
 [ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.
3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16.
16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.
0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]
 [ 0.  0.  0.  4. 15. 12.  0.  0.  0.  0.  3. 16. 15. 14.  0.  0.  0.  0.
8. 13.  8. 16.  0.  0.  0.  0.  1.  6. 15. 11.  0.  0.  0.  1.  8. 13.
15.  1.  0.  0.  0.  9. 16. 16.  5.  0.  0.  0.  0.  3. 13. 16. 16. 11.
5.  0.  0.  0.  0.  3. 11. 16.  9.  0.]
 [ 0.  0.  7. 15. 13.  1.  0.  0.  0.  8. 13.  6. 15.  4.  0.  0.  0.  2.
1. 13. 13.  0.  0.  0.  0.  0.  2. 15. 11.  1.  0.  0.  0.  0.  0.  1.
12. 12.  1.  0.  0.  0.  0.  0.  1. 10.  8.  0.  0.  0.  8.  4.  5. 14.
9.  0.  0.  0.  7. 13. 13.  9.  0.  0.]
 [ 0.  0.  0.  1. 11.  0.  0.  0.  0.  0.  0.  7.  8.  0.  0.  0.  0.  0.
1. 13.  6.  2.  2.  0.  0.  0.  7. 15.  0.  9.  8.  0.  0.  5. 16. 10.
0. 16.  6.  0.  0.  4. 15. 16. 13. 16.  1.  0.  0.  0.  0.  3. 15. 10.
0.  0.  0.  0.  0.  2. 16.  4.  0.  0.]]
The targets for the first 5 entries: [0 1 2 3 4]
The targets for the first 5 binary entries: (0, 1, 0, 1, 0)
 
```

We can then use the restricted data and targets datasets as input to our
function, assuming your function `binary_digit_clf()`:


```py
confuse_mx = binary_digit_clf(bd,bt,test_size=0.95)
print(f'Confusion matrix:\n{confuse_mx}')
disp = metrics.ConfusionMatrixDisplay(confusion_matrix=confuse_mx)
#Use a different color map since the default is garish:
disp.plot(cmap = "Purples")
plt.title("Logistic Regression Classifier for Binary Digits")
plt.show()
```


which will print:


```text
Confusion matrix:
[[172   0]
 [  4 166]]
```


and display:


![log_confusion](../attachments/logReg_clf_confuse.png)

Another example with the same data, but different size for the data
reserved for testing:


```py
confuse_mx = binary_digit_clf(bd,bt)
print(f'Confusion matrix:\n{confuse_mx}')
```


would print:


```py
Confusion matrix:
[[43  0]
 [ 0 47]]
```

*Note*: you should submit a file with only the standard comments at the
top, and this function. The grading scripts will then import the file
for testing. If you attended lecture, include in the introductory
comment the three lines detailed in Classwork 2.

## Week 10

### Classwork 13.2

Using [Google Maps API](https://developers.google.com/maps/documentation/distance-matrix/overview), we generated the amount of time it would take to travel between the following landmarks:
- Bronx Zoo (Bronx),
- Empire State Building (Manhattan),
- National Lighthouse Museum (Staten Island),
- FDR Four Freedoms Park (Roosevelt Island),
- Citi Field (Queens),
- Coney Island (Brooklyn), and
- Hunter College (Manhattan)

by driving, transit, and walking (files: [nyc_landmarks_driving.csv](../attachments/nyc_landmarks_driving.csv), [nyc_landmarks_transit.csv](../attachments/nyc_landmarks_transit.csv), [nyc_landmarks_walking.csv](../attachments/nyc_landmarks_walking.csv)).

Of the three, which best estimates the (aerial) distance?

![nyc_landmarks_distance.png](../attachments/nyc_landmarks.png)

# Week 12
## Classwork 15:   
*Monday, 17 November.*   
Write a program that asks the user for the name of an input HTML file and the name of an output CSV file. Your program should use regular expressions (see Chapter 12.4 for using the re package in Python) to find all links in the input file and store the link text and URL as columns: Title and URL in the CSV file specified by the user. For the URL, strip off the leading https:// or http:// and any trailing slashes (/):

For example, if the input file is:


``` text
<html>
<head><title>Simple HTML File</title></head>

<body>
  <p> Here's a link for <a href="http://www.hunter.cuny.edu/csci">Hunter CS Department</a>
  and for <a href="https://stjohn.github.io/teaching/data/fall21/index.html">CSci 39542</a>.  </p>

  <p> And for <a href="https://www.google.com/">google</a>
</body>
</html>
```

Then a sample run of the program:

```text
Enter input file name: simple.html
Enter output file name:  links.csv
```


And the links.csv would be:


```text
Title,URL
Hunter CS Department,www.hunter.cuny.edu/csci
CSci 39542,stjohn.github.io/teaching/data/fall21/index.html
google,www.google.com
```


Note: you should submit a file with only the standard comments at the top that you attended lecture in the introductory comment (see Classwork 2 for details). The grading scripts will run your program directly on several different test cases, supplying the names of the files. If you do not ask for input in your program (e.g. ask for the input and output file names), the autograder will time-out waiting.